title: Charlie (Chihpin) Lu.  # Add a space after the period

logo: pic.png # Use a relative path to logo image 

description: degree with both computer science and electrical engineering. 
 
email: chihpinjobhunt@gmail.com # Allow visitors to contact you
